insert into OUTLET(OUTLET_ID,OUTLET_NAME,OUTLET_RADIUS,OUTLET_INDUSTRY) values(1,'NIKE',1,'FASHION');
insert into OUTLET(OUTLET_ID,OUTLET_NAME,OUTLET_RADIUS,OUTLET_INDUSTRY) values(2,'ADIDAS',6,'FASHION');
insert into OUTLET(OUTLET_ID,OUTLET_NAME,OUTLET_RADIUS,OUTLET_INDUSTRY) values(3,'PUMA',11,'FASHION');
insert into OUTLET(OUTLET_ID,OUTLET_NAME,OUTLET_RADIUS,OUTLET_INDUSTRY) values(4,'REDMI',2,'MOBILE');
insert into OUTLET(OUTLET_ID,OUTLET_NAME,OUTLET_RADIUS,OUTLET_INDUSTRY) values(5,'SAMSUNG',7,'MOBILE');
insert into OUTLET(OUTLET_ID,OUTLET_NAME,OUTLET_RADIUS,OUTLET_INDUSTRY) values(6,'OPPO',12,'MOBILE');
insert into OUTLET(OUTLET_ID,OUTLET_NAME,OUTLET_RADIUS,OUTLET_INDUSTRY) values(7,'STARBUCKS',3,'CAFE');
insert into OUTLET(OUTLET_ID,OUTLET_NAME,OUTLET_RADIUS,OUTLET_INDUSTRY) values(8,'CCD',8,'CAFE');
insert into OUTLET(OUTLET_ID,OUTLET_NAME,OUTLET_RADIUS,OUTLET_INDUSTRY) values(9,'BARISTA',14,'CAFE');

insert into OFFER(OFFER_NAME,OUTLET_ID,OFFER_ADDRESS,OFFER_PHONE) values('NIKE OFFER1',1,'11 Sholinganallur 603103','9840100001');
insert into OFFER(OFFER_NAME,OUTLET_ID,OFFER_ADDRESS,OFFER_PHONE) values('NIKE OFFER2',1,'11 Sholinganallur 603103','9840100002');
insert into OFFER(OFFER_NAME,OUTLET_ID,OFFER_ADDRESS,OFFER_PHONE) values('ADIDAS OFFER1',2,'11 Sholinganallur 603103','9840100002');
insert into OFFER(OFFER_NAME,OUTLET_ID,OFFER_ADDRESS,OFFER_PHONE) values('REDMI OFFER1',4,'22 Dollar 603103','9840100003');
insert into OFFER(OFFER_NAME,OUTLET_ID,OFFER_ADDRESS,OFFER_PHONE) values('REDMI OFFER2',4,'22 Dollar 603103','9840100004');
insert into OFFER(OFFER_NAME,OUTLET_ID,OFFER_ADDRESS,OFFER_PHONE) values('SAMSUNG OFFER1',5,'22 Dollar 603103','9840100004');
insert into OFFER(OFFER_NAME,OUTLET_ID,OFFER_ADDRESS,OFFER_PHONE) values('STARBUCKS OFFER1',7,'22 Karapakkam 603103','9840100003');
insert into OFFER(OFFER_NAME,OUTLET_ID,OFFER_ADDRESS,OFFER_PHONE) values('STARBUCKS OFFER2',7,'22 Karapakkam 603103','9840100004');
insert into OFFER(OFFER_NAME,OUTLET_ID,OFFER_ADDRESS,OFFER_PHONE) values('CCD OFFER1',8,'22 Karapakkam 603103','9840100004');

insert into RADIUS values(5);
insert into RADIUS values(10);
insert into RADIUS values(15);